// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_admin_update_username_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_admin_update_username_type));
        
        string IMigrationMetadata.Id
        {
            get { return "202203211541426_mig_admin_update_username_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
